[profile.default]
  src = "src"
  out = "out"
  libs = ["lib"]
  fs_permissions = [{access = "read-write", path = "./deployments"}]
  no_match_contract = 'CryticTester|Handler|Deploy'
evm_version = 'shanghai'

[invariant]
  runs = 1000
  fail_on_revert = false

[rpc_endpoints]
  sepolia = "${SEPOLIA_RPC_URL}"
  polygon = "${POLYGON_RPC_URL}"
  anvil = "http://127.0.0.1:8545"
[etherscan]
sepolia = { key = "${API_KEY_ETHERSCAN}" }
polygon = { key = "${API_KEY_POLYGONSCAN}" }

[fmt]
  sort_imports = true
  line_length = 120

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
